name: Build and Test Task 3

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setupup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build
        working-directory: ./java/src
        run: javac ./lab5/task_5_3/encoder/CharEncoder.java ./lab5/task_5_3/encoder/CharIncEncoder.java ./lab5/task_5_3/fs/FileEncodeSystem.java ./lab5/task_5_3/scanner/InputScanner.java ./lab5/task_5_3/menu/MenuStates.java ./lab5/task_5_3/menu/MenuView.java ./lab5/task_5_3/menu/MenuModel.java ./lab5/task_5_3/menu/MenuController.java ./lab5/task_5_3/Main.java

      - name: Test
        working-directory: ./java
        run: |
          javac -cp "./junit/junit-platform-console-standalone-1.9.0.jar" ./src/lab5/task_5_3/encoder/CharEncoder.java ./src/lab5/task_5_3/encoder/CharIncEncoder.java ./src/lab5/task_5_3/tests/EncoderTests.java
          java -jar ./junit/junit-platform-console-standalone-1.9.0.jar -cp "./src" --select-class lab5.task_5_3.tests.EncoderTests
